project:
  type: website
  output-dir: docs

website:
  favicon: logo.png
  title: "Data Cipher's Project Lab"
  navbar:
    search: true
    left:
      - text: Home
        href: index.qmd
      - text: Data
        href: data.qmd
      - text: Analysis
        href: analysis.qmd

            
    tools:
      - icon: github
        href: https://github.com/emu-hacettepe-analytics/emu430-fall2023-team-data_ciphers

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "Hacettepe IE - EMU 430 - Fall 2023" 
    border: true
format:
  html:
    toc: true
    toc-location: left
    theme: 
      light: flatly 
      dark: flatly
    css: styles.css


editor: visual

