---
title: "Analysis"
format:
  html:
    toc: true
    toc-depth: 6
    toc-title: Contents
    toc-location: left
    toc-expand: 5
    smooth-scroll: true
    anchor-sections: true
    include-after-body: abbrv_toc.html
    number-sections: true
---

# Full Analysis

## Data Set 1

```{r}
#| echo: false
suppressPackageStartupMessages(library(dplyr))
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)

data_1 <- read_excel("tidydataset1.xls")
colnames(data_1) <- c("Diseases", "men_2016", "women_2016", "men_2019", "women_2019", "men_2022", "women_2022")

data_1_longer <- data_1 %>%
  pivot_longer(cols = starts_with(c("men", "women")),
               names_to = "Gender",
               values_to = "Percentage") %>%
  separate(Gender, into = c("Gender", "Year"), sep = "_") %>%
  arrange(Diseases) %>%
  mutate_at(vars(Year, Percentage), as.numeric) %>%
  mutate(Diseases = gsub("^\\n", "", Diseases))
```

### Average Percentage by Disease {toc-text="Plot 1"}

```{r}
#| code-fold: true
#| code-summary: "Show the code"

abbreviate_disease_names <- abbreviate(data_1_longer$Diseases)
ggplot(data_1_longer, aes(x = Diseases, y = Percentage, fill = Diseases)) +
  geom_bar(stat = "summary", fun = "mean", position = "dodge") +
  labs(title = "Average Percentage by Disease",
       x = "Diseases",
       y = "Percantage") +
  scale_x_discrete(labels = abbreviate_disease_names) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

### Percentage by Gender {toc-text="Plot 2"}

```{r}
#| code-fold: true
#| code-summary: "Show the code"

ggplot(data_1_longer, aes(x = Diseases, y = Percentage, fill = Gender)) +
  geom_bar(stat = "identity") +
  labs(title = "Percentage by Gender",
       x = "Diseases",
       y = "Percentage") +
  scale_x_discrete(labels = abbreviate_disease_names) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

## Data Set 3

```{r}
#| echo: false
suppressPackageStartupMessages(library(dplyr))
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
data_3 <- read_excel("tidydataset3.xls")
colnames(data_3) <- c("Year", "Sex", "Underweight", "Normal_weight", "Pre_Obese", "Obese")
data_3_long <- data_3 %>%
  pivot_longer(cols = c(Underweight, Normal_weight, Pre_Obese, Obese),
               names_to = "Category",
               values_to = "Percentage")
```

### Percentage of Categories Over Years {toc-text="Plot 1"}

```{r}
#| code-fold: true
#| code-summary: "Show the code"
ggplot(data_3_long, aes(x = Year, y = Percentage, fill = Category)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Percentage of Categories Over Years",
       x = "Year",
       y = "Percentage") +
  theme_minimal()
```

### Percentage Trends Over Years {toc-text="Plot 2"}

```{r}
#| code-fold: true
#| code-summary: "Show the code"
ggplot(data_3_long, aes(x = Year, y = Percentage, color = Category)) +
  geom_line() +
  labs(title = "Percentage Trends Over Years",
       x = "Year",
       y = "Percentage") +
  theme_minimal()
```

### Composition of Categories Over Years {toc-text="Plot 3"}

```{r}
#| code-fold: true
#| code-summary: "Show the code"
ggplot(data_3_long, aes(x = Year, y = Percentage, fill = Category)) +
  geom_area() +
  labs(title = "Composition of Categories Over Years",
       x = "Year",
       y = "Percentage") +
  theme_minimal()
```

### Percentage of Categories by Gender {toc-text="Plot 4"}

```{r}
#| code-fold: true
#| code-summary: "Show the code"
ggplot(data_3_long, aes(x = Sex, y = Percentage, fill = Category)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(title = "Percentage of Categories by Gender",
       x = "Gender",
       y = "Percentage") +
  theme_minimal()
```
